
services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile  
    container_name: node_app
    restart: always
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://postgres:password@postgres:5432/mydb
    command: ["npm", "run", "start:migrate:prod"]
    volumes:
      - pgdata:/var/lib/postgresql/data  
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
